steps:
  - name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/fresh-bloom-438819-i4/spring-boot-rest:${SHORT_SHA}'
      - '-f'
      - './Dockerfile'
      - '.'

  - name: 'google/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud app deploy app.yaml --quiet || { echo 'Deployment failed' ; exit 1; }

  # Deploy API to Apigee
  - name: 'google/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud apigee api-proxies deploy --name your-api-proxy-name --quiet || { echo 'API deployment failed' ; exit 1; }

  # Terraform step (initialize and apply)
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd terraform-directory && terraform init && terraform apply -auto-approve || { echo 'Terraform apply failed' ; exit 1; }

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - gcr.io/fresh-bloom-438819-i4/spring-boot-rest:${SHORT_SHA}
