steps:
  - name: 'maven:3.9.9-eclipse-temurin-21'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'google/cloud-sdk'
    entrypoint: 'bash'
    args:
        - '-c'
        - |
          gcloud app deploy app.yaml --quiet

# Enable automatic regional log bucket creation
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - gcr.io/fresh-bloom-438819-i4/spring-boot-rest:${SHORT_SHA}
